spring:
  application.name: bankemployee
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    validate-on-migrate: true
    default-schema: public
