openapi: "3.0.1"
info:
  version: 1.0.0
  title: Swagger Backend API for bank employees
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /accounts:
    post:
      summary: Create an account
      operationId: createAccount
      tags:
        - accounts
      requestBody:
        description: Request body to create a new account
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Newly created account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        '400':
          description: Client error
        '500':
          description: unexpected error
  /accounts/{accountId}:
    get:
      summary: Info for a specific account
      operationId: getAccountById
      tags:
        - accounts
      parameters:
        - name: accountId
          in: path
          required: true
          description: The id of the account to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        '404':
          description: Account not found
        '500':
          description: unexpected error
  /transasctions:
    post:
      summary: Create a transaction between accounts
      operationId: createTransaction
      tags:
        - transactions
      requestBody:
        description: Request body to perform a transaction between accounts.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        '400':
          description: Client error
        '404':
          description: Account not found
        '500':
          description: unexpected error
components:
  schemas:
    AccountRequest:
      type: object
      required:
        - balance
      properties:
        balance:
          type: number
    AccountResponse:
      type: object
      required:
        - accountId
        - balance
      properties:
        accountId:
          type: string
          format: uuid
        balance:
          type: number
    TransactionRequest:
      type: object
      required:
        - fromAccountId
        - toAccountId
        - amount
      properties:
        fromAccountId:
          type: string
          format: uuid
        toAccountId:
          type: string
          format: uuid
        amount:
          type: number
    TransactionResponse:
      type: object
      required:
        - transactionId
        - amount
      properties:
        transactionId:
          type: string
          format: uuid
        amount:
          type: number
